version: '3.8'

services:
  postgres-kratos:
    image: docker.io/library/postgres:16-alpine
    ports:
      - '${DB_PORT:-5431}:5432'
    volumes:
      - 'kratos-postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${DB_USERNAME:-postgres}',
          '-U',
          '${DB_PASSWORD:-postgres}',
        ]
      retries: 3
      timeout: 5s
    networks:
      - playground

  kratos-migrate:
    image: docker.io/oryd/kratos:v1.0.0
    depends_on:
      - postgres-kratos
    environment:
      - DSN=postgres://postgres:postgres@postgres-kratos:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - playground

  kratos:
    image: docker.io/oryd/kratos:v1.0.0
    depends_on:
      - kratos-migrate
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:postgres@postgres-kratos:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config/kratos/email-password
        target: /etc/config/kratos
    networks:
      - playground

  kratos-selfservice-ui-node:
    image: docker.io/oryd/kratos-selfservice-ui-node:v0.13.0-20
    depends_on:
      - kratos
    restart: on-failure
    ports:
      - 4435:4435
    environment:
      - PORT=4435
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
      - COOKIE_SECRET=playground12345
      - CSRF_COOKIE_NAME=__locahost-example.com-x-csrf-token
      - CSRF_COOKIE_SECRET=playground12345
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    networks:
      - playground

  oathkeeper:
    image: docker.io/oryd/oathkeeper:v0.40.6
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - playground
    volumes:
      - ./config/oathkeeper:/etc/config/oathkeeper

volumes:
  kratos-postgres:
  kratos-sqlite:
