version: '3'
services:
  postgres:
    image: docker.io/library/postgres:14-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${DB_USERNAME:-postgres}',
          '-U',
          '${DB_PASSWORD:-postgres}',
        ]
      retries: 3
      timeout: 5s

  redis:
    image: docker.io/library/redis:6-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

  minio:
    image: docker.io/minio/minio
    ports:
      - '${S3_PORT:-9000}:9000'
      - '${S3_CONSOLE_PORT:-8900}:8900'
    volumes:
      - 'minio-data:/data/minio'
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-miniosudo}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-miniosudo}
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:9000/minio/health/live']
      retries: 3
      timeout: 5s

  minio-client:
    image: docker.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${S3_ACCESS_KEY_ID:-miniosudo} ${S3_SECRET_ACCESS_KEY:-miniosudo};
      /usr/bin/mc rm -r --force myminio/local;
      /usr/bin/mc mb myminio/local;
      /usr/bin/mc policy set download myminio/local;
      exit 0;
      "

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'

volumes:
  postgres-data:
  redis-data:
  minio-data:
