name: CI - Node

on:
  push:
    branches:
      - "main"
      - "development"
    paths:
      - "node/**"
      - ".github/workflows/node.yml"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "node/**"
      - ".github/workflows/node.yml"

jobs:
  build:
    name: Build (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20']
    env:
      FOLDER: node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: ${{ env.FOLDER }}/yarn.lock

      - name: Install dependencies
        run: |
          cd ${{ env.FOLDER }}
          yarn install

      - name: Run linter
        run: |
          cd ${{ env.FOLDER }}
          yarn lint

      - name: Run prettier
        run: |
          cd ${{ env.FOLDER }}
          yarn prettier

      - name: Run build
        run: |
          cd ${{ env.FOLDER }}
          yarn build

      - name: Run tests
        run: |
          cd ${{ env.FOLDER }}
          cp .env.example .env
          docker compose up -d
          sleep 10s
          yarn migrate:up
          yarn seed:run
          yarn test
          docker compose down -v

